(function() {var implementors = {};
implementors["lua"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"lua/ffi/struct.lua_State.html\" title=\"struct lua::ffi::lua_State\">lua_State</a>",synthetic:false,types:["lua::ffi::lua_State"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"lua/ffi/struct.lua_Debug.html\" title=\"struct lua::ffi::lua_Debug\">lua_Debug</a>",synthetic:false,types:["lua::ffi::lua_Debug"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"lua/ffi/struct.luaL_Reg.html\" title=\"struct lua::ffi::luaL_Reg\">luaL_Reg</a>",synthetic:false,types:["lua::ffi::luaL_Reg"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"lua/ffi/struct.luaL_Buffer.html\" title=\"struct lua::ffi::luaL_Buffer\">luaL_Buffer</a>",synthetic:false,types:["lua::ffi::luaL_Buffer"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"lua/ffi/struct.__va_list_tag.html\" title=\"struct lua::ffi::__va_list_tag\">__va_list_tag</a>",synthetic:false,types:["lua::ffi::__va_list_tag"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"lua/ffi/struct.CallInfo.html\" title=\"struct lua::ffi::CallInfo\">CallInfo</a>",synthetic:false,types:["lua::ffi::CallInfo"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"lua/index/enum.Index.html\" title=\"enum lua::index::Index\">Index</a>",synthetic:false,types:["lua::index::Index"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"lua/userdata/enum.MetaMethod.html\" title=\"enum lua::userdata::MetaMethod\">MetaMethod</a>",synthetic:false,types:["lua::userdata::MetaMethod"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"lua/enum.Lib.html\" title=\"enum lua::Lib\">Lib</a>",synthetic:false,types:["lua::Lib"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
